# Configurações do banco de dados H2
spring:
  datasource:
    url: jdbc:h2:mem:testdbprodutos
    driver-class-name: org.h2.Driver
    username: teste
    password: teste

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2-ui